name: First workflow

on:
  push: 
    branches:
      - main
      
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      -name: Step one
       uses: actions/checkout@v2.3.4
      -name: Step two
       run: env | sort
       
       
   job2:
     runs-on: windows-latest
    steps:
     -name: Second job
       uses: actions/checkout@v2.3.4
      -name: Step two
       run: env | sort
