# This is a basic workflow to help you get started with Actions

name: First Step

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  job1:
      runs-on: ubuntu-latest
      steps:
       - name: First-job
         run: date
  job2:
       # This workflow contains a single job called "build"
    runs-on: windows-latest
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
        - name: step 1
          run: date
  job3:

      runs-on: macos-latest
      steps:
          - name: Second-job
            run: date  
  job4:
      runs-on: ubuntu-latest
      needs: [job1, job2, job3]
      steps:
          # Runs a set of commands using the runners shell
          - name: final step

